

import { Afacad_Flux } from 'next/font/google'
import "./globals.css";


const afacadFlux = Afacad_Flux({
  subsets: ['latin'],
  variable: '--font-afacad',
  display: 'swap',
})


export const metadata = {
  title: "MohammadPanahi",
  description: "Generated by Mmd himself",
};

export default function RootLayout({ children }) {


  
  return (
    <html lang="en">
      <body
        className={`${afacadFlux.variable} ${afacadFlux.variable} antialiased`}
      >
        {children}
        
      </body>
    </html>
  );
}
